### ISSUE TITLE
Serverside only crash on button break (last 1.15.2 version)

### ISSUE THREAD

**Issue by ValentinJD-Pro** [PianoManu/BlockCarpentry#22]
Everything is said in the title :

Stacktrace : java.lang.NoSuchMethodError: net.minecraft.item.Item.func_190903_i()Lnet/minecraft/item/ItemStack;
	at mod.pianomanu.blockcarpentry.block.ButtonFrameBlock.dropContainedBlock(ButtonFrameBlock.java:122) ~[?:1.15.1-0.8.1] {re:classloading}
	at mod.pianomanu.blockcarpentry.block.ButtonFrameBlock.func_196243_a(ButtonFrameBlock.java:145) ~[?:1.15.1-0.8.1] {re:classloading}
	at net.minecraft.block.BlockState.func_196947_b(BlockState.java:245) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:environs:environs_blockstate_transformer,pl:mixin:APP:phosphor.mixins.json:block.MixinBlockState,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:266) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:phosphor.mixins.json:chunk.MixinChunk,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_180501_a(World.java:177) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:218) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:167) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:268) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:241) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:216) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:140) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:833) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer,pl:mixin:A}
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}

full crash report : http://pastebin.fr/75721

**Comment by PianoManu** [comment]
Please update to a newer version of the mod. I fixed this bug some time ago

**Comment by ValentinJD-Pro** [comment]
No apparently it's still the last 1.15.2 version : blockcarpentry-1.15.1-0.8.1.jar

**Comment by PianoManu** [comment]
Oh, I saw it. Sorry. Seems I fixed it in all other versions and forgot the 1.15 version... Sorry

**Comment by PianoManu** [comment]
Can't believe I forgot to copy-paste two classes when back-porting. I just pushed my changes and I hope, it will work with the next version

**Comment by PianoManu** [comment]
I can't recreate that issue anymore, so I mark this as fixed. Thanks again for reporting!
