### ISSUE TITLE
ClassNotFoundException: net.minecraft.world.level.block.WoodButtonBlock on startup

### ISSUE THREAD

**Issue by pavog** [PianoManu/BlockCarpentry#70]
Hi, I'm using the latest version [BlockCarpentry 1.19 (0.1.1.1)](https://www.curseforge.com/minecraft/mc-mods/blockcarpentry/files/4094099) on my fresh new server with Forge 1.19.3 (44.1.0) and no other mods.

I get the following error on startup of my server:
"ClassNotFoundException: net.minecraft.world.level.block.WoodButtonBlock"

Full stack trace:

```
[modloading-worker-0/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
--
java.lang.ClassNotFoundException: net.minecraft.world.level.block.WoodButtonBlock
at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:92) ~[eventbus-6.0.3.jar%2352!/:?]
at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-6.0.3.jar%2352!/:?]
at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.3.jar%2352!/:?]
at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.3.jar%2352!/:6.0.3+6.0.3+master.039e4ea9]
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2355!/:?]
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2355!/:?]
at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2355!/:?]
at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
at mod.pianomanu.blockcarpentry.setup.Registration.<clinit>(Registration.java:92) ~[blockcarpentry-1.19-0.1.1.1.jar%23101!/:1.19-0.1.1.1]
at mod.pianomanu.blockcarpentry.BlockCarpentryMain.<init>(BlockCarpentryMain.java:52) ~[blockcarpentry-1.19-0.1.1.1.jar%23101!/:1.19-0.1.1.1]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.3-44.1.0.jar%23105!/:?]
at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.3-44.1.0.jar%23104!/:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
```

Full server log:
https://mclo.gs/1t5wxtz

**Comment by ProsperCraft** [comment]
Same Crash on 1.19.3

**Comment by PianoManu** [comment]
Does not work for 1.19.2 and 1.19.3. I had to take a break from the development, but I'll fix this asap

**Comment by PianoManu** [comment]
Forgot to answer when I fixed this issue. Mod versions for 1.19.3 and 1.19.4 are on curseforge 😄
