### ISSUE TITLE
Default Layed Block Creating Client Side Crash

### ISSUE THREAD

**Issue by Phelms215** [PianoManu/BlockCarpentry#72]
Hello! 

There is a client side crash for anyone  on our server when anyone in Survival attempts to break these two blocks when they have the default texture, if a texture is applied no crash is seen.  

blockcarpentry:frame_layered_block
blockcarpentry:illusion_layered_block

Let me know if you need anything more to help track this down 

`
[20:25:16] [Render thread/INFO]: Exception when loading blockcarpentry:frame_layered_block texture, using material colour.
[20:25:16] [Render thread/ERROR]: suppressed exception
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "net.minecraftforge.client.model.data.IModelData.getData(net.minecraftforge.client.model.data.ModelProperty)" is null
	at mod.pianomanu.blockcarpentry.bakedmodels.LayeredBlockEmptyBakedModel.getMimicQuads(LayeredBlockEmptyBakedModel.java:63) ~[blockcarpentry-1.18-0.3.0.jar%2364!/:1.18-0.3.0]
	at mod.pianomanu.blockcarpentry.bakedmodels.LayeredBlockEmptyBakedModel.getQuads(LayeredBlockEmptyBakedModel.java:45) ~[blockcarpentry-1.18-0.3.0.jar%2364!/:1.18-0.3.0]
	at xaero.map.MapWriter.loadBlockColourFromTexture(MapWriter.java:743) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.region.MapPixel.getPixelColours(MapPixel.java:50) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.region.Overlay.getPixelColour(Overlay.java:48) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.region.MapPixel.getPixelColours(MapPixel.java:102) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.region.MapBlock.getPixelColour(MapBlock.java:54) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.region.MapTileChunk.updateBuffers(MapTileChunk.java:87) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.MapWriter.writeChunk(MapWriter.java:462) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.MapWriter.writeMap(MapWriter.java:253) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.MapWriter.onRender(MapWriter.java:194) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.MapProcessor.onRenderProcess(MapProcessor.java:362) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.events.Events.renderTick(Events.java:93) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at net.minecraftforge.eventbus.ASMEventHandler_36_Events_renderTick_RenderTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onRenderTickEnd(ForgeEventFactory.java:869) ~[forge-1.18.2-40.1.93-universal.jar%23195!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1050) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.93.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
[20:25:17] [Render thread/INFO]: Exception when loading blockcarpentry:frame_layered_block texture, using material colour.
[20:25:17] [Render thread/ERROR]: suppressed exception
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "net.minecraftforge.client.model.data.IModelData.getData(net.minecraftforge.client.model.data.ModelProperty)" is null
	at mod.pianomanu.blockcarpentry.bakedmodels.LayeredBlockEmptyBakedModel.getMimicQuads(LayeredBlockEmptyBakedModel.java:63) ~[blockcarpentry-1.18-0.3.0.jar%2364!/:1.18-0.3.0]
	at mod.pianomanu.blockcarpentry.bakedmodels.LayeredBlockEmptyBakedModel.getQuads(LayeredBlockEmptyBakedModel.java:45) ~[blockcarpentry-1.18-0.3.0.jar%2364!/:1.18-0.3.0]
	at xaero.map.MapWriter.loadBlockColourFromTexture(MapWriter.java:743) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.region.MapPixel.getPixelColours(MapPixel.java:50) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.region.Overlay.getPixelColour(Overlay.java:48) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.region.MapPixel.getPixelColours(MapPixel.java:102) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.region.MapBlock.getPixelColour(MapBlock.java:54) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.region.MapTileChunk.updateBuffers(MapTileChunk.java:87) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.MapWriter.writeChunk(MapWriter.java:462) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.MapWriter.writeMap(MapWriter.java:253) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.MapWriter.onRender(MapWriter.java:194) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.MapProcessor.onRenderProcess(MapProcessor.java:362) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at xaero.map.events.Events.renderTick(Events.java:93) ~[XaerosWorldMap_1.28.7_Forge_1.18.2.jar%23188!/:1.28.7]
	at net.minecraftforge.eventbus.ASMEventHandler_36_Events_renderTick_RenderTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onRenderTickEnd(ForgeEventFactory.java:869) ~[forge-1.18.2-40.1.93-universal.jar%23195!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1050) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.93.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
[20:25:30] [Render thread/INFO]: Minimap session finalized.
[20:25:30] [Render thread/INFO]: Finalizing world map session...
[20:25:30] [Thread-25/INFO]: World map cleaned normally!
[20:25:30] [Render thread/INFO]: World map session finalized.
[20:25:30] [Render thread/INFO]: Released client Flux Networks cache
[20:25:30] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggedOutEvent
[20:25:30] [Render thread/INFO]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[20:25:30] [Render thread/INFO]: Stopping JEI
[20:25:38] [Render thread/INFO]: Stopping worker threads
[20:25:38] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:60) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBreakingTexture(BlockRenderDispatcher.java:56) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.m_110918_(BlockRenderDispatcher.java:50) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1302) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.93.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "net.minecraftforge.client.model.data.IModelData.getData(net.minecraftforge.client.model.data.ModelProperty)" is null
	at mod.pianomanu.blockcarpentry.bakedmodels.LayeredBlockEmptyBakedModel.getMimicQuads(LayeredBlockEmptyBakedModel.java:64) ~[blockcarpentry-1.18-0.3.0.jar%2364!/:1.18-0.3.0]
	at mod.pianomanu.blockcarpentry.bakedmodels.LayeredBlockEmptyBakedModel.getQuads(LayeredBlockEmptyBakedModel.java:45) ~[blockcarpentry-1.18-0.3.0.jar%2364!/:1.18-0.3.0]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateWithAO(ModelBlockRenderer.java:77) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.tesselateWithAO(ForgeBlockModelRenderer.java:77) ~[forge-1.18.2-40.1.93-universal.jar%23195!/:?]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	... 21 more
[20:25:38] [Render thread/FATAL]: Preparing crash report with UUID e4afb277-b796-4496-b414-381a5e26c0de
[20:25:38] [Render thread/FATAL]: Preparing crash report with UUID 8544b3b1-5258-46bc-9b14-6f1d1efeb96f
`

**Comment by PianoManu** [comment]
I am unable to reconstruct this issue. I also can't remember to have fixed this bug. Maybe I have already fixed it without noticing or I forgot, but I found another bug, which is that not all layers are dropping. So anyway, thanks for reporting!
Regards, Manu
